package com.flowerworld.app.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table FAVORITES.
 */
public class Favorites {

    private String ID;
    private Integer orderNum;
    private String favname;
    private String cityName;
    private String groupID;
    private String provinceName;
    private String company;
    private String companyLevel;
    private String home;
    private String des;

    public Favorites() {
    }

    public Favorites(String ID) {
        this.ID = ID;
    }

    public Favorites(String ID, Integer orderNum, String favname, String cityName, String groupID, String provinceName, String company, String companyLevel, String home, String des) {
        this.ID = ID;
        this.orderNum = orderNum;
        this.favname = favname;
        this.cityName = cityName;
        this.groupID = groupID;
        this.provinceName = provinceName;
        this.company = company;
        this.companyLevel = companyLevel;
        this.home = home;
        this.des = des;
    }

    public String getID() {
        return ID;
    }

    public void setID(String ID) {
        this.ID = ID;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getFavname() {
        return favname;
    }

    public void setFavname(String favname) {
        this.favname = favname;
    }

    public String getCityName() {
        return cityName;
    }

    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    public String getGroupID() {
        return groupID;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    public String getProvinceName() {
        return provinceName;
    }

    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getCompanyLevel() {
        return companyLevel;
    }

    public void setCompanyLevel(String companyLevel) {
        this.companyLevel = companyLevel;
    }

    public String getHome() {
        return home;
    }

    public void setHome(String home) {
        this.home = home;
    }

    public String getDes() {
        return des;
    }

    public void setDes(String des) {
        this.des = des;
    }

}
