package com.flowerworld.app.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table FRIEND_GROUP.
 */
public class FriendGroup {

    /**
     * Not-null value.
     */
    private String ID;
    private Integer orderNum;
    private String name;

    public FriendGroup() {
    }

    public FriendGroup(String ID) {
        this.ID = ID;
    }

    public FriendGroup(String ID, Integer orderNum, String name) {
        this.ID = ID;
        this.orderNum = orderNum;
        this.name = name;
    }

    /**
     * Not-null value.
     */
    public String getID() {
        return ID;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setID(String ID) {
        this.ID = ID;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
