package com.flowerworld.app.dao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table FRIEND.
 */
public class Friend {

    /**
     * Not-null value.
     */
    private String ID;
    private Integer orderNum;
    private String userName;
    private String realName;
    private String groupID;
    private String groupName;
    private String company;
    private String companyLevel;
    private String header;

    public Friend() {
    }

    public Friend(String ID) {
        this.ID = ID;
    }

    public Friend(String ID, Integer orderNum, String userName, String realName, String groupID, String groupName, String company,
            String companyLevel, String header) {
        this.ID = ID;
        this.orderNum = orderNum;
        this.userName = userName;
        this.realName = realName;
        this.groupID = groupID;
        this.groupName = groupName;
        this.company = company;
        this.companyLevel = companyLevel;
        this.header = header;
    }

    /**
     * Not-null value.
     */
    public String getID() {
        return ID;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setID(String ID) {
        this.ID = ID;
    }

    public Integer getOrderNum() {
        return orderNum;
    }

    public void setOrderNum(Integer orderNum) {
        this.orderNum = orderNum;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getRealName() {
        return realName;
    }

    public void setRealName(String realName) {
        this.realName = realName;
    }

    public String getGroupID() {
        return groupID;
    }

    public void setGroupID(String groupID) {
        this.groupID = groupID;
    }

    public String getGroupName() {
        return groupName;
    }

    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getCompanyLevel() {
        return companyLevel;
    }

    public void setCompanyLevel(String companyLevel) {
        this.companyLevel = companyLevel;
    }

    public String getHeader() {
        return header;
    }

    public void setHeader(String header) {
        this.header = header;
    }

}
